version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: stress_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: stress_monitoring
      MYSQL_USER: stress_user
      MYSQL_PASSWORD: stress123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: